const data = [
  {
    name: "Homer",
    image: "homer.png",
    kbd: 1,
    dataKey: 49,
  },
  {
    name: "Apu",
    image: "apu.png",
    kbd: 2,
    dataKey: 50,
  },
  {
    name: "Bart",
    image: "bart.png",
    kbd: 3,
    dataKey: 51,
  },
  {
    name: "Duffman",
    image: "duffman.png",
    kbd: 4,
    dataKey: 52,
  },
  {
    name: "Mr. Burns",
    image: "burns.png",
    kbd: 5,
    dataKey: 53,
  },
  {
    name: "Carl",
    image: "carl.png",
    kbd: 6,
    dataKey: 54,
  },
  {
    name: "Kent",
    image: "kent.png",
    kbd: 7,
    dataKey: 55,
  },
  {
    name: "Grandpa",
    image: "grandpa.png",
    kbd: 8,
    dataKey: 56,
  },
  {
    name: "Marge",
    image: "marge.png",
    kbd: 9,
    dataKey: 57,
  },
  {
    name: "Dr. Nick",
    image: "drnick.png",
    kbd: 0,
    dataKey: 48,
  },
  {
    name: "Comic Book Guy",
    image: "comicbookguy.png",
    kbd: "q",
    dataKey: 81,
  },
  {
    name: "Otto",
    image: "otto.png",
    kbd: "w",
    dataKey: 87,
  },
  {
    name: "Patty",
    image: "patty.png",
    kbd: "e",
    dataKey: 69,
  },
  {
    name: "Lisa",
    image: "lisa.png",
    kbd: "r",
    dataKey: 82,
  },
  {
    name: "Maggie",
    image: "maggie.png",
    kbd: "t",
    dataKey: 84,
  },
  {
    name: "Quimby",
    image: "quimby.png",
    kbd: "y",
    dataKey: 89,
  },
  {
    name: "Barney",
    image: "barney.png",
    kbd: "u",
    dataKey: 85,
  },
  {
    name: "Reverand Lovejoy",
    image: "lovejoy.png",
    kbd: "i",
    dataKey: 73,
  },
  {
    name: "Chief Wiggum",
    image: "wiggum.png",
    kbd: "o",
    dataKey: 79,
  },
  {
    name: "Ned",
    image: "ned.png",
    kbd: "p",
    dataKey: 80,
  },
  {
    name: "Principal Skinner",
    image: "skinner.png",
    kbd: "a",
    dataKey: 65,
  },
  {
    name: "Willy",
    image: "willy.png",
    kbd: "s",
    dataKey: 83,
  },
  {
    name: "Lunchlady Doris",
    image: "lunchladydoris.png",
    kbd: "d",
    dataKey: 68,
  },
  {
    name: "Cletus",
    image: "cletus.png",
    kbd: "f",
    dataKey: 70,
  },
  {
    name: "Waylon Smithers",
    image: "smithers.png",
    kbd: "g",
    dataKey: 71,
  },
  {
    name: "Mrs. Lovejoy",
    image: "mrslovejoy.png",
    kbd: "h",
    dataKey: 72,
  },
  {
    name: "Ralph",
    image: "ralph.png",
    kbd: "j",
    dataKey: 74,
  },
  {
    name: "Lyle",
    image: "lyle.png",
    kbd: "k",
    dataKey: 75,
  },

  {
    name: "Fat Tony",
    image: "fattony.png",
    kbd: "l",
    dataKey: 76,
  },
  {
    name: "Milhouse",
    image: "milhouse.png",
    kbd: "z",
    dataKey: 90,
  },
  {
    name: "Lenny",
    image: "lenny.png",
    kbd: "x",
    dataKey: 88,
  },
  {
    name: "Krusty",
    image: "krusty.png",
    kbd: "c",
    dataKey: 67,
  },
  {
    name: "Moe",
    image: "moe.png",
    kbd: "v",
    dataKey: 86,
  },
  {
    name: "Nelson",
    image: "nelson.png",
    kbd: "b",
    dataKey: 66,
  },
  {
    name: "Sideshow Bob",
    image: "sideshowbob.png",
    kbd: "n",
    dataKey: 78,
  },
  {
    name: "Troy",
    image: "troy.png",
    kbd: "m",
    dataKey: 77,
  },
  {
    name: "Couch",
    image: "couch.png",
    kbd: "space",
    dataKey: 32,
  },
  // {
  //   name: "Rod",
  //   image: "rod.png",
  //   kbd: "",
  // },
  // {
  //   name: "Selma",
  //   image: "selma.png",
  //   kbd: "",
  // },
  // {
  //   name: "Todd",
  //   image: "todd.png",
  //   kbd: "",
  // },
  // {
  //   name: "Maude",
  //   image: "maude.png",
  //   kbd: "",
  // },
  // {
  //   name: "Ms. Hoover",
  //   image: "mshoover.png",
  //   kbd: "",
  // },
  // {
  //   name: "Ms. Krabappel",
  //   image: "mskrabappel.png",
  //   kbd: "",
  // },
];

export default data;
