const data = [
  {
    name: "Homer",
    image: "homer.png",
    kbd: 1,
    source: "homer",
    dataKey: 49,
  },
  {
    name: "Apu",
    image: "apu.png",
    kbd: 2,
    source: "apu",
    dataKey: 50,
  },
  {
    name: "Bart",
    image: "bart.png",
    kbd: 3,
    source: "bart",
    dataKey: 51,
  },
  {
    name: "Duffman",
    image: "duffman.png",
    kbd: 4,
    source: "duffman",
    dataKey: 52,
  },
  {
    name: "Mr. Burns",
    image: "burns.png",
    kbd: 5,
    source: "burns",
    dataKey: 53,
  },
  {
    name: "Carl",
    image: "carl.png",
    kbd: 6,
    source: "carl",
    dataKey: 54,
  },
  {
    name: "Kent",
    image: "kent.png",
    kbd: 7,
    source: "kent",
    dataKey: 55,
  },
  {
    name: "Grandpa",
    image: "grandpa.png",
    kbd: 8,
    source: "grandpa",
    dataKey: 56,
  },
  {
    name: "Marge",
    image: "marge.png",
    kbd: 9,
    source: "marge",
    dataKey: 57,
  },
  {
    name: "Dr. Nick",
    image: "drnick.png",
    kbd: 0,
    source: "drnick",
    dataKey: 48,
  },
  {
    name: "Comic Book Guy",
    image: "comicbookguy.png",
    kbd: "q",
    source: "comicbookguy",
    dataKey: 113,
  },
  {
    name: "Otto",
    image: "otto.png",
    kbd: "w",
    source: "otto",
    dataKey: 119,
  },
  {
    name: "Patty",
    image: "patty.png",
    kbd: "e",
    source: "patty",
    dataKey: 101,
  },
  {
    name: "Lisa",
    image: "lisa.png",
    kbd: "r",
    source: "lisa",
    dataKey: 114,
  },
  {
    name: "Maggie",
    image: "maggie.png",
    kbd: "t",
    source: "maggie",
    dataKey: 116,
  },
  {
    name: "Quimby",
    image: "quimby.png",
    kbd: "y",
    source: "quimby",
    dataKey: 121,
  },
  {
    name: "Barney",
    image: "barney.png",
    kbd: "u",
    source: "barney",
    dataKey: 117,
  },
  {
    name: "Reverand Lovejoy",
    image: "lovejoy.png",
    kbd: "i",
    source: "lovejoy",
    dataKey: 105,
  },
  {
    name: "Chief Wiggum",
    image: "wiggum.png",
    source: "wiggum",
    kbd: "o",
    dataKey: 101,
  },
  {
    name: "Ned",
    image: "ned.png",
    kbd: "p",
    source: "ned",
    dataKey: 112,
  },
  {
    name: "Principal Skinner",
    image: "skinner.png",
    kbd: "a",
    source: "skinner",
    dataKey: 97,
  },
  {
    name: "Willy",
    image: "willy.png",
    kbd: "s",
    source: "willy",
    dataKey: 115,
  },
  {
    name: "Lunchlady Doris",
    image: "lunchladydoris.png",
    kbd: "d",
    source: "lunchladydoris",
    dataKey: 100,
  },
  {
    name: "Cletus",
    image: "cletus.png",
    kbd: "f",
    source: "cletus",
    dataKey: 102,
  },
  {
    name: "Waylon Smithers",
    image: "smithers.png",
    kbd: "g",
    source: "smithers",
    dataKey: 103,
  },
  {
    name: "Mrs. Lovejoy",
    image: "mrslovejoy.png",
    kbd: "h",
    source: "mrslovejoy",
    dataKey: 104,
  },
  {
    name: "Ralph",
    image: "ralph.png",
    kbd: "j",
    source: "ralph",
    dataKey: 106,
  },
  {
    name: "Lyle",
    image: "lyle.png",
    kbd: "k",
    source: "lyle",
    dataKey: 107,
  },

  {
    name: "Fat Tony",
    image: "fattony.png",
    kbd: "l",
    source: "fattony",
    dataKey: 108,
  },
  {
    name: "Milhouse",
    image: "milhouse.png",
    kbd: "z",
    source: "milhouse",
    dataKey: 122,
  },
  {
    name: "Lenny",
    image: "lenny.png",
    kbd: "x",
    source: "lenny",
    dataKey: 120,
  },
  {
    name: "Krusty",
    image: "krusty.png",
    kbd: "c",
    source: "krusty",
    dataKey: 99,
  },
  {
    name: "Moe",
    image: "moe.png",
    kbd: "v",
    source: "moe",
    dataKey: 118,
  },
  {
    name: "Nelson",
    image: "nelson.png",
    kbd: "b",
    source: "nelson",
    dataKey: 98,
  },
  {
    name: "Sideshow Bob",
    image: "sideshowbob.png",
    kbd: "n",
    source: "sideshowbob",
    dataKey: 110,
  },
  {
    name: "Troy",
    image: "troy.png",
    kbd: "m",
    source: "troy",
    dataKey: 109,
  },
  {
    name: "Couch",
    image: "couch.png",
    kbd: "space",
    source: "theme",
    dataKey: 32,
  },
  // {
  //   name: "Rod",
  //   image: "rod.png",
  //   kbd: "",
  // },
  // {
  //   name: "Selma",
  //   image: "selma.png",
  //   kbd: "",
  // },
  // {
  //   name: "Todd",
  //   image: "todd.png",
  //   kbd: "",
  // },
  // {
  //   name: "Maude",
  //   image: "maude.png",
  //   kbd: "",
  // },
  // {
  //   name: "Ms. Hoover",
  //   image: "mshoover.png",
  //   kbd: "",
  // },
  // {
  //   name: "Ms. Krabappel",
  //   image: "mskrabappel.png",
  //   kbd: "",
  // },
];

export default data;
